# Generated by Django 5.2.12 on 2026-03-05 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0002_alter_materialtype_id_alter_pickuprequest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuprequest',
            name='estimated_quantity',
            field=models.CharField(max_length=100),
        ),
    ]
