# Generated by Django 5.2.12 on 2026-03-05 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0003_alter_pickuprequest_estimated_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='quantity_unit',
            field=models.CharField(blank=True, default='kg', max_length=20),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='estimated_quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
